### ISSUE TITLE
Graphs/Charts

### ISSUE THREAD

**Issue by krashanoff** [SB-Technology-Holdings-International/WateringWebClient#6]
Upon logging in, the usage page is broken, and has the existing tags for the graphs but lacks the actual infographic.  However, it does work when signed into with ████████@gmail.com.  I think this may be because of an unclosed tag or possibly because of cached data in your browser that you haven't cleared.

**Comment by SebastianBoyd** [comment]
Don't put my email on the issues @krashanoff

**Comment by SebastianBoyd** [comment]
Fixed

**Comment by krashanoff** [comment]
your email is in your profile lol

**Comment by SebastianBoyd** [comment]
I know
